apiVersion: "serving.kubeflow.org/v1beta1"
kind: "InferenceService"
metadata:
  namespace: mp
  name: "faster-rcnn-torchserve"

spec:
  predictor:
    pytorch:
      resources:
        limits:
          cpu: 2
          memory: 8Gi
        requests:
          cpu: 1
          memory: 4Gi
      runtimeVersion: 0.4.0
      storageUri: "https://models.blob.core.chinacloudapi.cn/cv-models/faster-rcnn-pytorch.zip"